name: Bug反馈
description: 使用过程中遇到了Bug？点击这里进行快速反馈
labels:
  - bug反馈
assignees:
  - lumirant
body:
  - type: markdown
    attributes:
      value: |
        请根据Bug发生情况，尽可能详细的填写以下信息。
  - type: input
    id: time
    attributes:
      label: 出现时间
      description: Bug出现的时间。
      placeholder: 'ex. 2023/9/10 12:00'
    validations:
      required: true
  - type: input
    id: themeVersion
    attributes:
      label: 主题版本
      description: |
        Bug发生时，你所使用的Ayakin主题版本。
      placeholder: ex. 1.0.0
    validations:
      required: true
  - type: input
    id: typechoVersion
    attributes:
      label: Typecho版本
      description: |
        Bug发生时，你所使用的Typecho版本。
      placeholder: ex. 侧栏
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 浏览器
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Internet Explorer（不受维护）
        - 其他（如有，请在下方填写）
    validations:
      required: true
  - type: input
    id: otherBrowser
    attributes:
      label: 其他浏览器
      description: |
        如果你在上一项选择了“其他”，请填写此项。
      placeholder: ex. Via
  - type: input
    id: bugInfo
    attributes:
      label: 网站上显示的错误信息
      description: |
        如果这个Bug影响到了网站的正常运行，页面上会显示一条或多条错误信息，你可以将它们复制下来，粘贴到此处。
      placeholder: 'ex. Failed opening required ''xxx.php'' (include_path=''.:'')'
    validations:
      required: false
  - type: textarea
    id: bugDetails
    attributes:
      label: 出现现象
      description: |
        请详细描述Bug发生的现象。
    validations:
      required: true
  - type: input
    id: time
    attributes:
      label: 你的称呼
      description: 如有需要，会使用该名字称呼你。
      placeholder: ex. lumirant
    validations:
      required: false
  - type: input
    id: time
    attributes:
      label: 你的邮箱
      description: 如有需要，会通过邮箱联系你。
      placeholder: ex. ayakin@example.com
    validations:
      required: false
  - type: checkboxes
    id: checkagain
    attributes:
      label: 请确认一下事项
      description: |
        1. 我承诺该Bug真实发生。
        2. 我的联系信息填写正确（如果有填写）。
      options:
        - label: 我已确认以上事项
          required: true
